/*"W.A.J. P to demonstrate multiple catch blocks, (one is to handle divide by zero exception and another one is to handle
ArrayIndexOutOfBoundException) 
int a [] =new int [5]; a [5]=30/0;"
 */

package assignment;

public class A37 {

	public static void main(String[] args) {
		int a[]=new int[5];
		
		try {
			a[5]=30/0;
		}
		catch(ArithmeticException e) {
			System.out.println("cannot divide by zero");
		}
		catch (ArrayIndexOutOfBoundsException e) {
			System.out.println(e);
		}
	}
}
